name: Swift CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Swift PM Dependencies
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build Package (iOS Simulator)
      run: swift build -v -Xswiftc -target -Xswiftc arm64-apple-ios17.0-simulator

    - name: Run Tests (iOS Simulator)
      run: swift test -v -Xswiftc -target -Xswiftc arm64-apple-ios17.0-simulator
